= README

WARNING: This is just an adhoc project I am using to document api differences
between rewrite-clj* apis.

== Introduction

It has been many moons since I started merging rewrite-cljs and rewrite-clj into
rewrite-cljc.

Being both careful and forgetful, I thought I'd give myself some assurance that
rewrite-cljc has not broken rewrite-cljs and/or rewrite-clj apis in any
unintended way.

Hence this little hacky project.

== Goals

I'd like to compare the following apis:

* rewrite-clj and rewrite-cljs - what was different before I started this work?
* rewrite-clj clj and rewrite-cljc clj - what did I change for rewrite-clj
  users?
* rewrite-cljs cljs and rewrite-cljc cljs - what did I change for rewrite-cljs
  users?
* rewrite-cljc cljs and rewrite-cljc clj - what are differences for cljs and clj
  users of rewrite-cljc

I am pretty sure I only want to see differences in apis. I don't really care
what is the same. I also don't care to compare filenames, line numbers or doc
strings.

I'd like to include these comparisons in the rewrite-cljc documentation, so
generating a report to asciidoc would be ideal.

=== TODOS
. add license
. add circleci
. handle arglists regex case, eg https://github.com/cljdoc/cljdoc/issues/143, and example:
+
----
([{:keys [mappify keyify header transform-header remove-comments comment-re comment-char structs cast-fns cast-exception-handler cast-only]
     :or   {mappify         true
            keyify          true
            remove-comments true
            comment-re      #"^\#"}
----
I don't need this for my purposes, but worth handling for completeness, I think.
. consider a more unique namespace for this project
. test no diff scenario
. include number of diffs, perhaps as a count of publics affected, would be nice
  to highlight potentially breaking changes:
.. deleted things
.. changed things
. implement :exclude-namespaces
. flesh out some more unit tests for diffings and asciidoc rendering but sleep
  on approach first, something simpler is in order.
. clean up
.. clean up asciidoc report - overly complicated/fragile right now.
.. manipulating the diff structure after the fact is downright awkward due wrapping markers
   perhaps a better approach would be to use metadata?

=== Usage

I currently work from the root dir of this repo.

In brief:

* Specify project and language (clj or cljs) for each api
* Api diff is written to stdout
* Logs are written to `./log` dir
* cljdoc-analyzer api files are cached to `./.diff-apis/.cache`, delete this dir to wipe the cache

==== comparing projects from maven repos

[source,shell]
----
clojure -m diff-apis.main \
  projects \
  rewrite-clj 0.6.1 clj \
  rewrite-cljs 0.4.4 cljs
----

==== comparing projects from files

The files are expected to be in cljdoc-analyzer format.

[source,shell]
----
clojure -m diff-apis.main \
  files \
  rewrite-clj-0.6.1.pretty.edn clj \
  rewrite-cljs-0.4.4.pretty.edn cljs
----

==== options

* `--include` Either `:all` or `:changed-publics`, defaults to `:changed-publics`.
  I am not interested in namespaces where nothing has changed so I used `:changed-publics`
* `--exclude-namespace` Fully qualified namespace to exclude, repeat option for multiple
* `--report-format` Either `:asciidoc` or `:deep-diff`, defaults to `:deep-diff`
** `:deep-diff` a nice ANSI colorized diff of apis in edn.  I use this for quick checks and debugging
** `:asccidoc` an asciidoc version of api diffs. Tries to look ok-ish on github and good on cljdoc.
   I will include these in rewrite-cljc historical docs.

Example using options:

[source,shell]
----
clojure -m diff-apis.main \
  projects \
  rewrite-clj 0.6.1 clj \
  rewrite-cljs 0.4.4 cljs \
  --include :changed-publics \
  --exclude-namespace rewrite-clj.potemkin \
  --exclude-namepsace rewrite-clj.parser.utils \
  --report-format :asciidoc
----

=== Strategy

=== Tools
I'll get api data via https://github.com/lread/cljdoc-analyzer[cljdoc-analyzer].

https://github.com/lambdaisland/deep-diff[Kaocha deep-diff] looks like it might
give me a good start. Its pretty printer should allow me to verify during
development.

=== Changes
I will filter to the result to show only publics that have changes in them.

* A new/deleted ns will show the entire ns and all its publics.
* A ns with attributes changed only at the ns level will also show the entire
ns and all publics.
* A ns with changed publics will show the ns with all its attributes and the
  publics with changes in them. When there is a change in a public all values
  (including unchanged ones) for the public will be included for context.
* arglists will be compared with arity keys
* namespaces, publics and members will be compared on key of :name

=== Targets
Github supports no explicit colors for asciidoc. This will make reviewing diffs
on github a bit unpleasant. I'll likely suggest viewing the diffs on cljdoc.

Note that some folks use tricks on github to render colors. One of them is to
present text in a "diff" code block. This might be worth a few experiments as a
diff block could be directly relevant here. May try this, may not.

=== Future Possibilities

If this project does become generalized I will take the time to remedy the many
hacks it contains.
