version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-1.10.1.763

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "deps.edn"}}-
            - v1-dependencies- # fallback if cache not found

      - run:
          name: Dump tool versions
          command: clojure -e '(println (System/getProperty "java.runtime.name") (System/getProperty "java.runtime.version") "\nClojure" (clojure-version))'

      - run:
          name: Bring down the deps
          command: clojure -Spath

      - run:
          name: Lint
          command: script/lint

      - run:
          name: Run unit tests
          command: >
            clojure -M:test
            --reporter documentation
            --plugin kaocha.plugin/junit-xml
            --junit-xml-file target/test-results/unit/results.xml

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{checksum "deps.edn"}}

      - store_test_results:
          path: target/test-results

      - store_artifacts:
          path: target/test-results
