(ns diff-apis.report.asciidoc.header
  (:require [clojure.string :as string]
            [diff-apis.report.asciidoc.render :as render]))

(defn- project-as-code [p]
  (str "`+" (:project p) "+` `+" (:version p) "+` `+" (:lang p) "+`"))

(defn- project-as-text [p]
  (str "++" (:project p) " " (:version p) " " (:lang p) "++"))

(defn header-title [{:keys [projects]}]
  ["// This file was auto-generated by diff-apis, best not to edit"
   (str  "= Diff of "  (project-as-text (:a projects)) " & "  (project-as-text (:b projects)))
   ":toc: macro"
   ":toclevels: 5"
   ":!toc-title:"
   ""])

(defn- diff-overview [{:keys [projects]}]
  ["**Diff of apis in:**"
   ""
   (str  "A. "  (project-as-code (:a projects)))
   (str "B. "  (project-as-code (:b projects)))
   ""])

(defn- run-args [{:keys [run-args]}]
  ["With run-args:"
   "----"
   run-args
   "----"
   ""])

(defn- legend []
  ["**Legend:**"
   ""
   (str "* " (render/change-prefix :-)  (render/change-text :- "A only" ))
   (str "* " (render/change-prefix :+)  (render/change-text :+ "B only"))
   (str "* " (render/change-prefix :-)  (render/change-text :- "A is" )
        (render/change-prefix :+) (render/change-text :+ "different from B"))
   (str "* " (render/change-prefix nil) (render/change-text nil "changes within A and B"))
   (str "* " (render/change-prefix :=)  (render/change-text := "equal"))
   ""])

(defn- stat-row [stats k]
  [(str "| " (name k))
   (str "| " (get-in stats [:deletions k]))
   (str "| " (get-in stats [:mismatches k]))
   (str "| " (get-in stats [:insertions k]))
   ""])

(defn- stats [{:keys [stats]}]
  (-> ["**Stats:**"
       ""
       "|==="
       "| Element | Deletions | Mismatches | Insertions"
       ""]
      (into (flatten (for [k [:namespaces :publics :arglists]]
                       (stat-row stats k))))
      (into ["|==="])))

(defn header [result]
  (string/join "\n"
               (-> (header-title result)
                   (into (diff-overview result))
                   (into (run-args result))
                   (into (legend))
                   (into (stats result))
                   (into ["**Table of diffs:**"
                          ""
                          "toc::[]"
                          ""]))))
